name: Build and create cst-rakuten-backend package

on:
  push:
    branches:
      - homolog
      - main
jobs:
  build_and_publish:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - name: Set environment variables based on branch
        run: |
          if [[ "${GITHUB_REF##*/}" == "homolog" ]]; then
            echo "IMAGE_NAME=app-publisher-rakuten-homolog" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF##*/}" == "main" ]]; then
            echo "IMAGE_NAME=app-publisher-rakuten" >> $GITHUB_ENV
          fi
          echo "BRANCH=${GITHUB_REF##*/}"
      - name: Build and push image
        run: |
          docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.GH_PAT }} ghcr.io
          docker build -f ./infra/docker/Dockerfile.prod --tag ghcr.io/oondemand/${{env.IMAGE_NAME}}:0.0.1 .
          docker push ghcr.io/oondemand/${{env.IMAGE_NAME}}:0.0.1
